version: '3.9'

services:
  zookeeper:
    image: 'bitnami/zookeeper:3.9.2'
    container_name: zookeeper
    ports:
      - "2181:2181"
    environment:
       - ALLOW_ANONYMOUS_LOGIN=yes
    volumes:
      - zk_data:/bitnami/zookeeper/data
    restart: always

  kafka:
    image: 'bitnami/kafka:3.6.2'
    container_name: kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: true
    depends_on:
      - zookeeper
    volumes:
      - kafka_data:/var/lib/kafka/data
    restart: always

volumes:
  zk_data:
  kafka_data:

